@startuml

[:net:smack] --> [:core:api]

[:android:app] --> [:core:domain:app]
[:android:app] --> [:net:smack]
[:android:app] --> [:android:room]
[:android:app] --> [:android:dashboard]
[:android:app] --> [:android:chat]
[:android:app] --> [:android:account]
[:android:app] --> [:android:indicator]

[:android:account] --> [:android:core]
[:android:account] ---> [:core:domain:account]

[:android:chat] ---> [:android:core]
[:android:chat] --> [:core:domain:chat]

[:android:dashboard] --> [:android:roster]
[:android:dashboard] --> [:core:domain:dashboard]

[:android:roster] --> [:android:core]
[:android:roster] --> [:core:domain:chat]

[:android:indicator] ---> [:android:core]

[:android:core] --> [:core:domain:session]
[:android:core] --> [:core:domain:navigation]

[:android:room] --> [:core:api]



@enduml
