@startuml

[:net:smack] --> [:domain:api]

[:android:app] --> [:domain:app]
[:android:app] --> [:net:smack]
[:android:app] --> [:android:data]
[:android:app] --> [:android:dashboard]
[:android:app] --> [:android:chat]
[:android:app] --> [:android:account]
[:android:app] --> [:android:indicator]

[:android:account] --> [:android:core]
[:android:account] ---> [:domain:account]

[:android:chat] ---> [:android:core]
[:android:chat] --> [:domain:chat]

[:android:dashboard] --> [:android:roster]
[:android:dashboard] --> [:domain:dashboard]

[:android:roster] --> [:android:core]
[:android:roster] --> [:domain:chat]

[:android:indicator] ---> [:android:core]

[:android:core] --> [:domain:session]
[:android:core] --> [:domain:navigation]

[:android:data] --> [:domain:api]



@enduml