@startuml

[:net:smack] --> [:core:api]

[:android:app] --> [:core:app]
[:android:app] --> [:net:smack]
[:android:app] --> [:android:data]
[:android:app] --> [:android:dashboard]
[:android:app] --> [:android:chat]
[:android:app] --> [:android:account]
[:android:app] --> [:android:indicator]

[:android:account] --> [:android:core]
[:android:account] ---> [:core:account]

[:android:chat] ---> [:android:core]
[:android:chat] --> [:core:chat]

[:android:dashboard] --> [:android:roster]
[:android:dashboard] --> [:core:dashboard]

[:android:roster] --> [:android:core]
[:android:roster] --> [:core:chat]

[:android:indicator] ---> [:android:core]

[:android:core] --> [:core:session]
[:android:core] --> [:core:navigation]

[:android:data] --> [:core:api]



@enduml