@startuml

[:core:api]
[:core:common]
[:core:session]
[:core:account]
[:core:chat]
[:core:navigation]
[:core:roster]

[:core:common] --> [:core:api]
[:core:session] --> [:core:common]
[:core:navigation] --> [:core:common]
[:core:account] --> [:core:navigation]
[:core:account] --> [:core:session]
[:core:chat] --> [:core:navigation]
[:core:roster] --> [:core:common]

@enduml