@startuml

[:domain:api]
[:domain:common]
[:domain:session]
[:domain:account]
[:domain:chat]
[:domain:navigation]
[:domain:roster]

[:domain:common] --> [:domain:api]
[:domain:session] --> [:domain:common]
[:domain:navigation] --> [:domain:common]
[:domain:account] --> [:domain:navigation]
[:domain:account] --> [:domain:session]
[:domain:chat] --> [:domain:navigation]
[:domain:roster] --> [:domain:common]

@enduml