@startuml

[:engine:api]
[:engine:util:common]
[:engine:domain:session]
[:engine:domain:account]
[:engine:domain:chat]
[:engine:domain:navigation]
[:engine:domain:roster]

[:engine:util:common] --> [:engine:api]
[:engine:domain:session] --> [:engine:util:common]
[:engine:domain:navigation] --> [:engine:util:common]
[:engine:domain:account] --> [:engine:domain:navigation]
[:engine:domain:account] --> [:engine:domain:session]
[:engine:domain:chat] --> [:engine:domain:navigation]
[:engine:domain:roster] --> [:engine:util:common]

@enduml