@startuml
package ":core" {
[:core:backend]
[:core:domain]
[:core:api]
[:core:cli]
}
package ":platform" {
[:platform:net:smack:android]
[:platform:repo:room]
[:platform:sys:android]
[:platform:log:android]
[:platform:util:android:notification]
}
package ":android" {
[:android:error]
[:android:main]
[:android:indicator]
[:android:core]
[:android:resources]
[:android:debug]
[:android:intent]
[:android:account]
[:android:roster]
[:android:chat]
[:android:drawer]
[:android:widget]
[:android:app]
}
package ":engine" {
[:engine:paging]
[:engine:connectable]
[:engine:util]
[:engine:log]
[:engine:translator]
}
[:core:backend] --> [:core:domain]
[:platform:net:smack:android] --> [:core:api]
[:platform:repo:room] --> [:core:api]
[:platform:sys:android] --> [:android:indicator]
[:platform:log:android] --> [:engine:log]
[:android:error] --> [:engine:log]
[:android:main] --> [:android:debug]
[:android:main] --> [:android:intent]
[:android:main] --> [:android:account]
[:android:main] --> [:android:roster]
[:android:main] --> [:android:chat]
[:android:main] --> [:android:drawer]
[:android:main] --> [:core:domain]
[:core:domain] --> [:engine:paging]
[:core:domain] --> [:core:api]
[:core:api] --> [:engine:connectable]
[:engine:connectable] --> [:engine:util]
[:engine:connectable] --> [:engine:log]
[:android:indicator] --> [:android:core]
[:android:indicator] --> [:platform:util:android:notification]
[:android:core] --> [:core:api]
[:android:core] --> [:android:resources]
[:android:debug] --> [:core:api]
[:android:debug] --> [:core:cli]
[:android:debug] --> [:android:core]
[:android:debug] --> [:android:widget]
[:android:intent] --> [:core:api]
[:android:account] --> [:android:core]
[:android:roster] --> [:android:core]
[:android:chat] --> [:android:core]
[:android:chat] --> [:platform:util:android:notification]
[:android:chat] --> [:android:widget]
[:android:chat] --> [:core:cli]
[:android:drawer] --> [:android:core]
[:core:cli] --> [:engine:translator]
[:core:cli] --> [:core:api]
[:android:widget] --> [:android:resources]
[:android:app] --> [:core:backend]
[:android:app] --> [:platform:net:smack:android]
[:android:app] --> [:platform:repo:room]
[:android:app] --> [:platform:sys:android]
[:android:app] --> [:platform:log:android]
[:android:app] --> [:android:error]
[:android:app] --> [:android:main]
@enduml
