@startuml
package ":core" {
[:core:backend]
[:core:domain]
[:core:api]
[:core:cli]
}
package ":net" {
[:net:smack:android]
}
package ":android" {
[:android:room]
[:android:sys]
[:android:log]
[:android:error]
[:android:main]
[:android:indicator]
[:android:core]
[:android:notification]
[:android:resources]
[:android:debug]
[:android:intent]
[:android:account]
[:android:roster]
[:android:chat]
[:android:drawer]
[:android:widget]
[:android:app]
}
package ":engine" {
[:engine:paging]
[:engine:connectable]
[:engine:util]
[:engine:log]
[:engine:translator]
}
[:core:backend] --> [:core:domain]
[:net:smack:android] --> [:core:api]
[:android:room] --> [:core:api]
[:android:sys] --> [:android:indicator]
[:android:log] --> [:engine:log]
[:android:error] --> [:engine:log]
[:android:main] --> [:android:debug]
[:android:main] --> [:android:intent]
[:android:main] --> [:android:account]
[:android:main] --> [:android:roster]
[:android:main] --> [:android:chat]
[:android:main] --> [:android:drawer]
[:android:main] --> [:core:domain]
[:core:domain] --> [:engine:paging]
[:core:domain] --> [:core:api]
[:core:api] --> [:engine:connectable]
[:engine:connectable] --> [:engine:util]
[:engine:connectable] --> [:engine:log]
[:android:indicator] --> [:android:core]
[:android:indicator] --> [:android:notification]
[:android:core] --> [:core:api]
[:android:core] --> [:android:resources]
[:android:debug] --> [:core:api]
[:android:intent] --> [:core:api]
[:android:account] --> [:android:core]
[:android:roster] --> [:android:core]
[:android:chat] --> [:android:core]
[:android:chat] --> [:android:notification]
[:android:chat] --> [:android:widget]
[:android:chat] --> [:core:cli]
[:android:drawer] --> [:android:core]
[:android:widget] --> [:android:resources]
[:core:cli] --> [:engine:translator]
[:core:cli] --> [:core:api]
[:android:app] --> [:core:backend]
[:android:app] --> [:net:smack:android]
[:android:app] --> [:android:room]
[:android:app] --> [:android:sys]
[:android:app] --> [:android:log]
[:android:app] --> [:android:error]
[:android:app] --> [:android:main]
@enduml
