@startuml
package ":core" {
[:core:backend]
[:core:domain]
[:core:api]
[:core:cli]
}
package ":platform" {
[:platform:net:smack:android]
[:platform:repo:room]
[:platform:sys:android]
[:platform:log:android]
[:platform:repo:data]
[:platform:util:android:indicator]
[:platform:util:android:notification]
}
package ":app" {
[:app:android:error]
[:app:android:main]
[:app:android:debug]
[:app:android:intent]
[:app:android:account]
[:app:android:roster]
[:app:android:chat]
[:app:android:drawer]
[:app:android:core]
[:app:android:widget]
[:app:android:resources]
[:app:android:app]
}
package ":engine" {
[:engine:paging]
[:engine:connectable]
[:engine:util]
[:engine:log]
[:engine:cli]
}
[:core:backend] --> [:core:domain]
[:platform:net:smack:android] --> [:core:api]
[:platform:repo:room] --> [:core:api]
[:platform:repo:room] --> [:platform:repo:data]
[:platform:sys:android] --> [:platform:util:android:indicator]
[:platform:log:android] --> [:engine:log]
[:app:android:error] --> [:engine:log]
[:app:android:main] --> [:app:android:debug]
[:app:android:main] --> [:app:android:intent]
[:app:android:main] --> [:app:android:account]
[:app:android:main] --> [:app:android:roster]
[:app:android:main] --> [:app:android:chat]
[:app:android:main] --> [:app:android:drawer]
[:app:android:main] --> [:core:domain]
[:core:domain] --> [:engine:paging]
[:core:domain] --> [:core:api]
[:core:api] --> [:engine:connectable]
[:engine:connectable] --> [:engine:util]
[:engine:connectable] --> [:engine:log]
[:platform:repo:data] --> [:core:api]
[:platform:util:android:indicator] --> [:core:api]
[:platform:util:android:indicator] --> [:platform:util:android:notification]
[:app:android:debug] --> [:core:api]
[:app:android:debug] --> [:core:cli]
[:app:android:debug] --> [:app:android:core]
[:app:android:debug] --> [:app:android:widget]
[:app:android:intent] --> [:core:api]
[:app:android:account] --> [:app:android:core]
[:app:android:roster] --> [:app:android:core]
[:app:android:chat] --> [:app:android:core]
[:app:android:chat] --> [:platform:util:android:notification]
[:app:android:chat] --> [:app:android:widget]
[:app:android:chat] --> [:core:cli]
[:app:android:drawer] --> [:app:android:core]
[:core:cli] --> [:engine:cli]
[:core:cli] --> [:core:api]
[:app:android:core] --> [:core:api]
[:app:android:core] --> [:app:android:resources]
[:app:android:widget] --> [:app:android:resources]
[:app:android:app] --> [:core:backend]
[:app:android:app] --> [:platform:net:smack:android]
[:app:android:app] --> [:platform:repo:room]
[:app:android:app] --> [:platform:sys:android]
[:app:android:app] --> [:platform:log:android]
[:app:android:app] --> [:app:android:error]
[:app:android:app] --> [:app:android:main]
@enduml
