@startuml
package ":platform" {
[:platform:repo:mock]
[:platform:net:mock]
[:platform:sys:mock]
[:platform:net:smack:jvm]
[:platform:log:jvm]
}
package ":core" {
[:core:backend]
[:core:api]
[:core:domain]
}
package ":engine" {
[:engine:net]
[:engine:connectable]
[:engine:util]
[:engine:log]
[:engine:paging]
[:engine:json]
}
package ":jvm" {
[:jvm:server]
}
[:platform:repo:mock] --> [:core:api]
[:platform:net:mock] --> [:core:api]
[:platform:sys:mock] --> [:core:api]
[:platform:net:smack:jvm] --> [:core:api]
[:core:backend] --> [:core:domain]
[:engine:net] --> [:engine:connectable]
[:engine:net] --> [:engine:json]
[:platform:log:jvm] --> [:engine:log]
[:core:api] --> [:engine:connectable]
[:engine:connectable] --> [:engine:util]
[:engine:connectable] --> [:engine:log]
[:core:domain] --> [:engine:paging]
[:core:domain] --> [:core:api]
[:jvm:server] --> [:platform:repo:mock]
[:jvm:server] --> [:platform:net:mock]
[:jvm:server] --> [:platform:sys:mock]
[:jvm:server] --> [:platform:net:smack:jvm]
[:jvm:server] --> [:core:backend]
[:jvm:server] --> [:engine:net]
[:jvm:server] --> [:platform:log:jvm]
@enduml
