@startuml
[:engine:net] --> [:engine:connectable]
[:engine:net] --> [:engine:json]
[:jvm:log] --> [:engine:log]
[:core:cli] --> [:engine:translator]
[:core:cli] --> [:core:api]
[:engine:connectable] --> [:engine:util]
[:engine:connectable] --> [:engine:log]
[:core:api] --> [:engine:connectable]
[:jvm:cli] --> [:engine:net]
[:jvm:cli] --> [:jvm:log]
[:jvm:cli] --> [:core:cli]
@enduml
