@startuml
package ":core" {
[:core:cli]
[:core:api]
}
package ":engine" {
[:engine:net]
[:engine:cli]
[:engine:connectable]
[:engine:util]
[:engine:log]
[:engine:json]
}
package ":platform" {
[:platform:log:jvm]
}
package ":app" {
[:app:jvm:cli]
}
[:core:cli] --> [:engine:cli]
[:core:cli] --> [:core:api]
[:engine:net] --> [:engine:connectable]
[:engine:net] --> [:engine:json]
[:platform:log:jvm] --> [:engine:log]
[:core:api] --> [:engine:connectable]
[:engine:connectable] --> [:engine:util]
[:engine:connectable] --> [:engine:log]
[:app:jvm:cli] --> [:core:cli]
[:app:jvm:cli] --> [:engine:net]
[:app:jvm:cli] --> [:platform:log:jvm]
@enduml
