@startuml
[:core:mock:repo] --> [:core:api]
[:core:mock:net] --> [:core:api]
[:core:mock:sys] --> [:core:api]
[:net:smack:jvm] --> [:core:api]
[:core:backend] --> [:core:domain:app]
[:core:backend] --> [:core:domain:session]
[:core:backend] --> [:core:domain:account]
[:core:backend] --> [:core:domain:chat]
[:core:backend] --> [:core:domain:roster]
[:engine:net] --> [:engine:connectable]
[:engine:net] --> [:engine:json]
[:jvm:log] --> [:engine:log]
[:core:api] --> [:engine:connectable]
[:engine:connectable] --> [:engine:util]
[:engine:connectable] --> [:engine:log]
[:core:domain:app] --> [:core:api]
[:core:domain:session] --> [:core:api]
[:core:domain:account] --> [:core:api]
[:core:domain:chat] --> [:engine:paging]
[:core:domain:roster] --> [:engine:paging]
[:jvm:server] --> [:core:mock:repo]
[:jvm:server] --> [:core:mock:net]
[:jvm:server] --> [:core:mock:sys]
[:jvm:server] --> [:net:smack:jvm]
[:jvm:server] --> [:core:backend]
[:jvm:server] --> [:engine:net]
[:jvm:server] --> [:jvm:log]
@enduml
