@startuml
[:core:api] --> [:engine:connectable]
[:core:api] --> [:engine:log]
[:core:backend] --> [:core:domain:app]
[:core:backend] --> [:core:domain:session]
[:core:backend] --> [:core:domain:account]
[:core:backend] --> [:core:domain:chat]
[:core:backend] --> [:core:domain:roster]
[:core:mock:net] --> [:core:api]
[:net:smack:android] --> [:core:api]
[:android:room] --> [:core:api]
[:android:sys] --> [:android:core]
[:android:sys] --> [:android:notification]
[:android:sys] --> [:android:indicator]
[:android:sys] --> [:core:api]
[:android:sys] --> [:engine:log]
[:android:log] --> [:engine:log]
[:android:error] --> [:engine:log]
[:android:main] --> [:android:intent]
[:android:main] --> [:android:account]
[:android:main] --> [:android:roster]
[:android:main] --> [:android:chat]
[:android:main] --> [:android:drawer]
[:android:main] --> [:core:domain:app]
[:android:core] --> [:core:api]
[:android:core] --> [:android:debug]
[:android:chat] --> [:android:core]
[:android:chat] --> [:android:notification]
[:android:chat] --> [:android:widget]
[:android:chat] --> [:core:cli]
[:android:roster] --> [:android:core]
[:engine:connectable] --> [:engine:util]
[:engine:connectable] --> [:engine:log]
[:core:domain:app] --> [:core:api]
[:core:domain:session] --> [:core:api]
[:core:domain:session] --> [:engine:connectable]
[:core:domain:account] --> [:core:api]
[:core:domain:chat] --> [:engine:paging]
[:core:domain:chat] --> [:engine:connectable]
[:core:domain:roster] --> [:core:api]
[:core:domain:roster] --> [:engine:paging]
[:core:domain:roster] --> [:core:mock:repo]
[:core:domain:roster] --> [:core:mock:net]
[:engine:paging] --> [:core:api]
[:core:mock:repo] --> [:core:api]
[:android:indicator] --> [:android:core]
[:android:indicator] --> [:android:notification]
[:android:intent] --> [:core:api]
[:android:intent] --> [:engine:log]
[:android:account] --> [:android:core]
[:android:drawer] --> [:android:core]
[:core:cli] --> [:engine:translator]
[:core:cli] --> [:core:api]
[:android:app] --> [:core:api]
[:android:app] --> [:core:backend]
[:android:app] --> [:core:mock:net]
[:android:app] --> [:net:smack:android]
[:android:app] --> [:android:room]
[:android:app] --> [:android:sys]
[:android:app] --> [:android:log]
[:android:app] --> [:android:error]
[:android:app] --> [:android:main]
[:android:app] --> [:android:core]
[:android:app] --> [:android:chat]
[:android:app] --> [:android:roster]
@enduml
