name: Release lastest

on: [ workflow_dispatch ]
#on:
#  push:
#    branches: [ master ]

jobs:
  snapshot-release:
    name: Snapshot Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Decrypt signing.properties
      run: ./ops/bash/decrypt_signing_properties.sh ${{ secrets.SECRET_KEY }}

    - name: Update latest notes
      run: |
        git config user.name "yang"
        git config user.email "cryptopunkyang@pm.me"
        ./ops/bash/update-latest-notes.sh
        git add latest_notes.md version.code version.hash version.name
        git commit -m "Snapshot `cat ./version.code`"
        git push

    - name: Build crypton apk
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        arguments: "clean android:app:assembleRemoteRelease"

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          android/app/build/outputs/apk/**/*.apk
