name: Build pull request

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        arguments: "clean assembleDebug"

    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
