name: Release
#name: Release tagged

#on:
#  push:
#    tags:
#      - 'v*'

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Decrypt signing.properties
      run: ./ops/bash/decrypt_signing_properties.sh ${{ secrets.SECRET_KEY }}

    - name: Update release notes
      run: ./ops/bash/update-relese-notes.sh

    - run: git push

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build android client apk
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        arguments: "clean android:app:assembleRemoteRelease"

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          android/app/build/outputs/apk/**/*.apk
