name: Prepare Version

on:
  push:
    branches: [ master ]

jobs:
  prepare-version:
    name: Prepare Version
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Assert version
      run: |
        . .env
        assert-version

    - name: Cancel running workflows
      uses: everphone-gmbh/cancel-previous-workflows@v5
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Update version notes
      run: |
        . .env
        decrypt-signing-properties ${{ secrets.SECRET_KEY }}
        ci-configure-git
        ci-set-git-token ${{ secrets.GITHUB_TOKEN }}
        ci-prepare-version
        cat release_notes.md
