name: Release Snapshot

on:
  push:
    tags:
      - "latest"

jobs:
  release-snapshot:
    name: Release Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Decrypt signing.properties
      run: |
        . .env
        decrypt-signing-properties ${{ secrets.SECRET_KEY }}

    - name: Build crypton apk
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        arguments: "clean app:android:app:assembleRemoteRelease app:jvm:embedded:shadowJar"

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          app/android/app/build/outputs/apk/**/*.apk
          app/jvm/embedded/build/libs/*.jar

    - id: get-body
      run: |
        export BODY="$(cat latest_notes.md)"
        BODY="${BODY//'%'/'%25'}"
        BODY="${BODY//$'\n'/'%0A'}"
        BODY="${BODY//$'\r'/'%0D'}"
        echo "::set-output name=snapshot-body::${BODY}"

    - name: Update Release Body
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "latest"
        body: ${{ steps.get-body.outputs.snapshot-body }}
        allow_override: true
