name: Release Snapshot

on:
  push:
    tags:
      - "latest"

jobs:
  release-snapshot:
    name: Release Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Decrypt signing.properties
      run: |
        . .env
        decrypt-signing-properties ${{ secrets.SECRET_KEY }}

    - name: Build crypton apk
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        arguments: "clean android:app:assembleRemoteRelease"

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          android/app/build/outputs/apk/**/*.apk
