name: Release Version

on:
  push:
    tags:
      - "v*"

jobs:
  release-version:
    name: Release Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Decrypt signing.properties
      run: |
        . .env
        decrypt-signing-properties ${{ secrets.SECRET_KEY }}
        echo ::set-env name=VERSION_NAME::"$(version-name)"

    - name: Build android client apk
      uses: eskatos/gradle-command-action@v1.3.2
      with:
        arguments: "clean app:android:app:assembleRemoteRelease"

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.VERSION_NAME }}
        prerelease: false
        files: |
          app/android/app/build/outputs/apk/**/*.apk
